[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "AWholeS"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.26.26"
]
# Review other keywords in:
# https://setuptools.pypa.io/en/latest/references/keywords.html

[project.optional-dependencies]
dev = ["pip-tools>=6.11.0"]

[tool.setuptools]
packages = ["AWholeS"]
