AWSTemplateFormatVersion: 2010-09-09
Description: Template containing an admin role

Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "AdminRole"
      Description: "Powerful admin role"
      MaxSessionDuration: 43200 # 12 hours
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sts:AssumeRole

  AdminPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: admin-access
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - !Ref AdminRole
